name: flutter_docs_scanner
description: "A Flutter plugin for iOS and Android allowing to scan documents using your camera."
version: 0.0.2
repository: https://github.com/AlexStrNik/flutter_docs_scanner
homepage: https://github.com/AlexStrNik/flutter_docs_scanner

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  camera: ^0.11.0+2
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: xyz.alexstrnik.flutter_docs_scanner
        pluginClass: FlutterDocsScannerPlugin
      ios:
        pluginClass: FlutterDocsScannerPlugin
